Fix Pinia 2.3 error caused by undeclared state variable (#1249)
After upgrading to Pinia 2.3.0, we started getting the error
  TypeError: can't access property "effect" of undefined
This was apparently caused by a state variable that was added
to the store at runtime without being declared/initialized beforehand.
Declaring the var in the state fixed the issue.